name: download-pro
#自动更新trcker版本
on:
  gollum
  #workflow_dispatch: # 手动触发
jobs:
  AutoDownloaderProcess:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2.1.0
    - name: Rclone Install
      run: curl https://rclone.org/install.sh | sudo bash
    - name: Aria2 Install
      run: sudo apt install -y aria2
    - name: Inject Rclone&Aria2 config
      run: |
        mkdir -p ~/.config/rclone/
        cat >  ~/.config/rclone.conf  << EOF
        ${{ secrets.RCLONE_CONF }}
        EOF
        cd ~/
        git clone https://github.com/winkxx/plz-download
        chmod +x ~/plz-download -R
        #rm -rf ~/plz-download
        cd ~/plz-download/config
        chmod 0777 ~/plz-download/config/tracker.sh
        /bin/bash ~/plz-download/config/tracker.sh 
    - name: Aria2_Downloading_File
      run: |
        cd ~/
        git clone "https://github.com/${GITHUB_REPOSITORY}.wiki.git"
        wiki=`echo $GITHUB_REPOSITORY | cut -d "/" -f 2`.wiki
        cd $wiki
        mdfile=`git log --pretty=format: -1 --name-only *.md`
        cd ..
        aria2c --seed-time=0 --conf-path=/home/runner/plz-download/config/aria2.conf -d downloads `cat $wiki/$mdfile | xargs`
        echo "${mdfile:0:-3}:" > DEST
        
    - name: Rclone Synchronizing file
      run: |
        #rclone copy downloads `cat DEST'
        #rclone copy -P downloads bfpan:Aria2D/里番
        rclone copy -P downloads xinyi:heroku
    - name: Delete workflow runs
      uses: GitRML/delete-workflow-runs@main
      with:
        retain_days: 1
        keep_minimum_runs: 3
