name: 全能下载
on:
  workflow_dispatch: # 手动触发
jobs:
  AutoDownloaderProcess:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2.1.0
    - name: Rclone Install
      run: curl https://rclone.org/install.sh | sudo bash
    - name: Aria2 Install
      run: sudo apt install -y aria2
    - name: Inject Rclone&Aria2 config
      run: |
        mkdir -p ~/.config/rclone/
        cat >  ~/.config/rclone.conf  << EOF
        ${{ secrets.RCLONE_CONF }}
        EOF
        mkdir -p ~/.aria2/
        touch ~/.aria2/aria2.session
        chmod 0777 ~/.aria2/ -R
        cd ~/
        git clone https://github.com/winkxx/plz-download
        chmod 0777 ~/plz-download
        mv ~/plz-download/config/* ~/.aria2/
        rm -rf ~/plz-download
        cd ~/.aria2/
        chmod 0777 ~/.aria2/tracker.sh
        /bin/bash ~/.aria2/tracker.sh 
    - name: Aria2_Downloading_File
      run: |
        git clone "https://github.com/${GITHUB_REPOSITORY}.wiki.git"
        wiki=`echo $GITHUB_REPOSITORY | cut -d "/" -f 2`.wiki
        cd $wiki
        mdfile=`git log --pretty=format: -1 --name-only *.md`
        cd ..
        aria2c --seed-time=0 -d downloads `cat $wiki/$mdfile | xargs`
        echo "${mdfile:0:-3}:" > DEST
